# Section 3
### Data science question 1: 
Is there a correlation between a country's heath expenditures and their rate of malnourishment in the most recent year with available data? 

This question is imploring as to whether there is a relationship between a country's health expenditures and their rate of malnutritioned children under 59 months. There will be either a positive correlation, meaning a higher health expenditure is associated with higher rates of malnutrition, a negative correlation, meaning a lower health expenditure is associated with higher rates of malnutrition, or no correlation. The rate of malnutrition refers to the total percentage of children who qualify for each type of malnutrition: wasting, stunting, overweight, and underweight. 

My data analysis method starts with calculating the total malnutrition rate of each country's children. I did this by totaling the percentages in each column describing a type of malnutrition: severe wasting, wasting, stunting, overweight, and underweight. I then looked through the health expenditures data frame to determine that 2018 was the most recent year with available data. The next step in my method created a dataframe to use for the scatterplot by joining the health expenditures of 2018 with the newly-created column of total malnutrition rates, matched by country. Lastly, I used this dataframe to create a scatterplot comparing malnourishment rates to health expenditures, each "dot" on the scatterplot being a country. The scatterplot I produced is shown below:

```{r part_2, echo=FALSE}
plot(correlation_plot)
```

Evaluation: 
It appears that there is no correlation between malnourishment rate and health expenditure of a country, which is surprising because I expected that higher health expenditures would be associated with lower rates of malnourishment. Logically, a country with higher health expenditures would likely be investing in better healthcare that addresses health issues such as malnourishment, so it seems like it should have a correlation with lower rates of malnourishment. However, according to this scatterplot, it shows no distinct relationship. The values are all dispersed throughout the plot, with no clear clustering in any direction. If there were a correlation, then the scatterplot should show at least a vague formation in a line. Because this is clearly not present in the scatterplot I produced, we can conclude that there is not a significant correlation between health expenditures and malnourishment rates. This indicates that increasing health expenditures, such as investing more in healthcare, will not necessarily lead to a decrease in malnourishment. 

